exports.actions = {
  RESET_LEAGUES_LIST: 'RESET_LEAGUES_LIST',
  ADD_LEAGUE: 'ADD_LEAGUE',
  REMOVE_FACILITY: 'REMOVE_FACILITY',

  ADD_LEAGUE_TEAM: 'ADD_LEAGUE_TEAM',
  REMOVE_LEAGUE_TEAM: 'REMOVE_LEAGUE_TEAM',
  ADD_LEAGUE_FACILITY: 'ADD_LEAGUE_FACILITY',
  REMOVE_LEAGUE_FACILITY: 'REMOVE_LEAGUE_FACILITY'
};
